### ISSUE TITLE
Get name of the video instead of 'audio'/'video' for downloaded file/s

### ISSUE THREAD

**Issue by queroin** [vot/urlgent#5]
It's not actually an issue but rather an improvement. It's just hassle to rename the downloaded file/s every time you download it 👍 But yeah, you rock 👍

Sample of downloaded audio:
![image](https://user-images.githubusercontent.com/31497266/46459274-fc104700-c7ea-11e8-9ac8-4dadf2945ccf.png)

**Comment by 0c0de** [comment]
can I take it?

**Comment by vot** [comment]
Hi @0c0de,

Absolutely, any help is appreciated :)
The main thing to do here will be to create an additional route handler for  `GET /stream/:id/:type/:niceName`. Probably worth moving existing handler to a function which could be used from both routes (existing one and the new one).

The behaviour should be as following:
1) When viewing a video in the context of the page the URL should remain the same (for the sake of privacy).
2) Clicking a button to open the resource in a new tab should use the title returned by `youtube-dl` and append it as a last segment (along with the correct extension).

This way we maintain a reasonable level of privacy AND we provide a better file name when the user chooses to reach the file through a direct link.

Let me know if you need any additional information, I'll be happy to provide it.

**Comment by 0c0de** [comment]
Ok then I will start this afternoon here in Spain is 10:30 and I have things to do but I'll do this afternoon thanks for the info :smile:

**Comment by 0c0de** [comment]
Ok what i've done (but i dont know if this is ok) it is that I created a new route with the name you suggested which is the same as ```/stream/:id/:type``` but what does it's just changes name to youtube-dl title... :sweat_smile:  if you don't understand me here's the code:

```javascript
app.get('/api/v2/stream/:id/:type/:niceName', function (req, res) {
    Helpers.logRequest('FILE_STREAM');
    const id = req.params.id;
    const type = req.params.type;

    JobLib.get(id, function (err, job) {
      if (!job || !Object.keys(job).length) {
        return res.status(404).send('Job not found.');
      }

      const mediaObject = _.get(job, 'data.media', {})[type];
      if (!mediaObject || !mediaObject.urlRaw) {
        return res.status(404).send('Media type not found.');
      }
      //Here is where I change the title
      const title = "youtube-dl-" + _.get(job, 'data.title').replace(/\s/g, "");
      req.params.niceName = title;
      request(mediaObject.urlRaw).pipe(res);
    });
  });
``` 
This is the url I get in my web browser
![finalResult](https://user-images.githubusercontent.com/6597723/46633224-542dad00-cb4d-11e8-823e-a74415cc8fdc.png)

Which is something like that
```http://localhost:3000/api/v2/stream/2aa760eb-535b-481a-9118-c29a9e51d843/audio/youtube-dl-PedroCap%C3%B3,Farruko-Calma(Remix-OfficialVideo)```

It's that what you requested? :thinking:

**Comment by vot** [comment]
Hi @0c0de,

Many thanks for this.

This approach already ticks a few of the necessary boxes. A few things I'd like to see changed:
- Use `ext` key from `mediaObject` to add the extension at the end of that route.
- Skip the `youtube-dl` prefix
- Enforce a filename as a redirection (when the niceName param doesn't match the title generated you could do `return res.redirect(url)` instead of  `req.params.niceName = title;`). This will always enforce that the name is what the service is returning
- Update the "Open audio/video in a new tab" buttons to also include the name (search for `urlProxied` to find all links to files)

**Comment by vot** [comment]
PS I'd be happy to take a look at a Pull Request once you put the code on a branch - these conversations are easier in that context :)

**Comment by 0c0de** [comment]
I made a PR.

**Comment by vot** [comment]
Hi @queroin & @0c0de,

This has now been merged to master and released at urlgent.com.
Thanks both, much appreciated :+1:

PS Happy Hacktoberfest!

**Comment by queroin** [comment]
Hello @vot 😀 
I think the problem is still persisting on your other download button. 

There is another download button though when you play the audio on the same page 👇 
![image](https://user-images.githubusercontent.com/31497266/49437471-90e8ee00-f7f6-11e8-82e8-708b17b7d768.png)
Once I download from that ⬆️ it still names the downloaded file `audio.webm`

Happy Holidays @vot!
